name: flutter_template
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

# 依赖库
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: 3.3.1
  camera: ^0.11.0+2
  cookie_jar: 4.0.8
  cupertino_icons: 1.0.2
  date_format: 2.0.2
  devicelocale: 0.8.1
  dio: ^5.7.0
  dio_cookie_manager: ^3.1.1
  extended_image: 8.1.2
  event_bus: 2.0.0
  # firebase_messaging: ^15.1.5 TODO: downdgrade
  floor: ^1.4.2
  flutter_easyrefresh: any
  flutter_spinkit: 5.0.0
  #flutter_webview_plugin: any
  #flutter_xupdate: 3.0.0
  #oktoast: 3.4.0
  path: ^1.9.0
  path_provider: 2.1.5
  #package_info: 2.0.2
  package_info_plus: ^8.1.0
  permission_handler: 11.3.1
  provider: 6.1.2
  shared_preferences: 2.3.2
  #share: 2.0.1
  url_launcher: ^6.0.2
  #image_gallery_saver: 2.0.3
  flutter_riverpod: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2 # floor build
  change_app_package_name: ^1.4.0
  floor_generator: ^1.4.2
  i18n_json: ^1.0.0
  

# 字体、图标、图片等资源加载
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: xuifont
      fonts:
        - asset: assets/fonts/iconfont.ttf